### ISSUE TITLE
pre-flight checklist

### ISSUE THREAD

**Issue by soundyogi** [lidont/lidont#54]
- [ ] deploy: withdrawler
- [ ] deploy: lidont
- [ ] set emission rate + toggle emissions on
- [ ] set admin
- [ ] deploy eth pipe
- [ ] deploy reth pipe
- [ ] activate pipes
- [ ] seek incentives for reth pipe, and add them
- [ ] check frontend + add deployment addresses to frontend
- [ ] add disclaimer: alpha - do not use 
- [ ] deposit some steth in both pipes
- [ ] wait cycle
- [ ] cycle again
- [ ] advertise/announce
- [ ] create multisig to be admin, choose and add signers etc. (devs / rocketpool community / mavericks )
- [ ] create fomo (x10 emissions for a week, airdrop for first 100 stakers, etc.)
